- src/tsurugi_utility/drop_index/drop_index_executor.cpp
- src/tsurugi_utility/include/drop_index.h
- src/tsurugi_utility/include/drop_index_executor.h
- src/tsurugi_utility/tsurugi_utility.c
Secondary index operations are not yet supported.
~~~
DROP DATABASE
ALTER DATABASE
test test_preparation             ... ok           11 ms
test create_table                 ... ok          179 ms
test insert_select_happy          ... ok          763 ms
test update_delete                ... ok          382 ms
test select_statements            ... ok          722 ms
test user_management              ... ok          198 ms
test udf_transaction              ... ok         2094 ms
test prepare_statment             ... ok          683 ms
test prepare_select_statment      ... …
> Secondary index operations are not yet supported.

- Makefile
- expected/data_types.out
- sql/data_types.sql
Fixed that data types not supported by tsurugi_fdw could be defined with CREATE TABLE.
~~~
DROP DATABASE
ALTER DATABASE
test test_preparation             ... ok           18 ms
test create_table                 ... ok          798 ms
test create_index                 ... ok         1590 ms
test insert_select_happy          ... ok          905 ms
test update_delete                ... ok          621 ms
test select_statements            ... ok          830 ms
test user_management              ... ok          211 ms
test udf_transaction              ... ok          954 ms …
> Fixed that data types not supported by tsurugi_fdw could be defined with CREATE TABLE.

- expected/create_table.out
- sql/create_table.sql
- src/tsurugi_fdw/tsurugi_utils.cpp
Fixed to erase standard (public) schema name from query string.
https://github.com/project-tsurugi/tsurugi-issues/issues/568
~~~log
DROP DATABASE
ALTER DATABASE
test test_preparation             ... ok           11 ms
test create_table                 ... ok          893 ms
test create_index                 ... ok         1575 ms
test insert_select_happy          ... ok         1025 ms
test update_delete                ... ok          640 ms
test select_statements            ... ok          907 ms
test user_management              ... ok          235 ms
test …
> Fixed to erase standard schema name from query string.

- docs/udf_reference/tg_set_exclusive_read_areas.md
- docs/udf_reference/tg_set_inclusive_read_areas.md
- docs/udf_reference/tg_set_transaction.md
- docs/udf_reference/tg_set_write_preserve.md
- docs/udf_reference/tg_show_transaction.md
- expected/manual_tutorial.out
- expected/prepare_select_statment.out
- expected/udf_transaction.out
- sql/prepare_select_statment.sql
- src/tsurugi_udf/tsurugi_udf.cpp
Enhanced entry of empty reservation tables in transaction options.
~~~
DROP DATABASE
ALTER DATABASE
test test_preparation             ... ok           19 ms
test create_table                 ... ok          812 ms
test create_index                 ... ok         1463 ms
test insert_select_happy          ... ok          938 ms
test update_delete                ... ok          585 ms
test select_statements            ... ok          834 ms
test user_management              ... ok          233 ms
test udf_transaction              ... ok          883 ms
test …
> Enhanced entry method for empty reservation tables.

- expected/insert_select_happy.out
- sql/insert_select_happy.sql
- src/tsurugi_planner/tsurugi_planner.c
Fixed issue that exception if multiple rows were specified for INSERT VALUES.
https://github.com/project-tsurugi/tsurugi-issues/issues/770
~~~log
DROP DATABASE
ALTER DATABASE
test test_preparation             ... ok           13 ms
test create_table                 ... ok          841 ms
test create_index                 ... ok         1535 ms
test insert_select_happy          ... ok          966 ms
test update_delete                ... ok          624 ms
test select_statements            ... ok          972 ms
test user_management              ... ok          216 ms …
> Fixed issue that exception if multiple rows were specified for INSERT VALUES.

- .github/actions/install-dependencies/action.yml
- expected/prepare_select_statment.out
- sql/prepare_select_statment.sql
Fixed a regression tests failure that oucurre due to a specification change in Tsurugi1.0.0-BETA6.
(https://github.com/project-tsurugi/tsurugi-issues/issues/69, https://github.com/project-tsurugi/tsurugi-issues/issues/70)
~~~log
DROP DATABASE
ALTER DATABASE
test test_preparation             ... ok           10 ms
test create_table                 ... ok          781 ms
test create_index                 ... ok         1498 ms
test insert_select_happy          ... ok          878 ms
test update_delete                ... ok          558 ms
test select_statements …
> Fixed a regression tests failure that oucurre due to a specification change in Tsurugi1.0.0-BETA6.

- expected/prepare_select_statment.out
- expected/select_statements.out
- sql/prepare_select_statment.sql
- sql/select_statements.sql
- src/tsurugi_fdw/deparse.c
Fixed the rewriting process of the elements in the GROUP BY clause.
https://github.com/project-tsurugi/tsurugi-issues/issues/958
~~~
DROP DATABASE
ALTER DATABASE
test test_preparation             ... ok           12 ms
test create_table                 ... ok          761 ms
test create_index                 ... ok         1418 ms
test insert_select_happy          ... ok         1033 ms
test update_delete                ... ok          571 ms
test select_statements            ... ok          519 ms
test user_management              ... ok          215 ms
test …
> Fixed the rewriting process of the elements in the GROUP BY clause.

- .gitmodules
Changed the submodule repository to a public repository using HTTPS.
https://github.com/project-tsurugi/tsurugi-issues/issues/913#issuecomment-2345300654
~~~
DROP DATABASE
ALTER DATABASE
test test_preparation             ... ok           19 ms
test create_table                 ... ok          772 ms
test create_index                 ... ok         1441 ms
test insert_select_happy          ... ok         1009 ms
test update_delete                ... ok          565 ms
test select_statements            ... ok          491 ms
test user_management              ... ok …
> Changed the submodule repository to a public repository using HTTPS.

- expected/user_management.out
- src/tsurugi_utility/tsurugi_utility.c
Unhooked the user management and access control.
~~~
DROP DATABASE
ALTER DATABASE
test test_preparation             ... ok           28 ms
test create_table                 ... ok          113 ms
test create_index                 ... ok           68 ms
test insert_select_happy          ... ok          308 ms
test update_delete                ... ok          227 ms
test select_statements            ... ok          154 ms
test user_management              ... ok           22 ms
test udf_transaction              ... ok          510 ms
test prepare_statment             ... …
> Unhooked the user management and access control.

- src/tsurugi_utility/tsurugi_utility.c
Fixed erroneous restriction on CREATE MATERIALIZED VIEW.
```
DROP DATABASE
ALTER DATABASE
test test_preparation             ... ok           29 ms
test create_table                 ... ok          112 ms
test create_index                 ... ok           69 ms
test insert_select_happy          ... ok          305 ms
test update_delete                ... ok          203 ms
test select_statements            ... ok          131 ms
test user_management              ... ok           22 ms
test udf_transaction              ... ok          471 ms
test prepare_statment …
```
> Fixed erroneous restriction on CREATE MATERIALIZED VIEW.

- docs/appendixes.md
- src/tsurugi_utility/tsurugi_utility.c
Added limitations of PREPARE to the document.
~~~
DROP DATABASE
ALTER DATABASE
test test_preparation             ... ok           32 ms
test create_table                 ... ok          109 ms
test create_index                 ... ok           70 ms
test insert_select_happy          ... ok          280 ms
test update_delete                ... ok          196 ms
test select_statements            ... ok          131 ms
test user_management              ... ok           21 ms
test udf_transaction              ... ok          488 ms
test prepare_statment             ... ok …
> Updated the document.

- docs/appendixes.md
- expected/prepare_statment.out
- expected/test_preparation.out
- scripts/create_tsurugi_tables.sql
- scripts/drop_tsurugi_tables.sql
- sql/prepare_statment.sql
- sql/test_preparation.sql
- src/tsurugi_fdw/tsurugi_fdw.cpp
- src/tsurugi_utility/prepare_execute/prepare_execute.cpp
Removed constraints other than set operators from the PREPARE command.
- \<set-quantifier> (ALL/DISTINCT) for SELECT
- LIMIT clause for SELECT
- DEFAULT VALUES for INSERT
- \<query-expression> for INSERT
~~~log
DROP DATABASE
ALTER DATABASE
test test_preparation             ... ok           30 ms
test create_table                 ... ok          112 ms
test create_index                 ... ok           91 ms
test insert_select_happy          ... ok          295 ms
test update_delete                ... ok          204 ms
test select_statements            ... ok …
> Removed some constraints from the PREPARE command.

- expected/insert_select_happy.out
Change the error content (test expectations) of tsurugi-issues#896 from tsurugi 1.3.0.
https://github.com/project-tsurugi/tsurugi-issues/issues/896#issuecomment-2713625566
~~~
DROP DATABASE
ALTER DATABASE
test test_preparation             ... ok           51 ms
test create_table                 ... ok          112 ms
test create_index                 ... ok           68 ms
test insert_select_happy          ... ok          308 ms
test update_delete                ... ok          202 ms
test select_statements            ... ok          133 ms
test user_management …
> Change the error content (test expectations) of tsurugi-issues#896

- expected/prepare_select_statment.out
- expected/select_statements.out
- sql/prepare_select_statment.sql
- sql/select_statements.sql
Disable the LIKE clause tests due to ongoing implementation.
https://github.com/project-tsurugi/tsurugi-issues/issues/1078
https://github.com/project-tsurugi/eisen/issues/10
~~~log
DROP DATABASE
ALTER DATABASE
test test_preparation             ... ok           31 ms
test create_table                 ... ok          111 ms
test create_index                 ... ok           69 ms
test insert_select_happy          ... ok          290 ms
test update_delete                ... ok          196 ms
test select_statements            ... ok          130 ms
test user_management …
> Disable the LIKE clause tests due to ongoing implementation.

- src/tsurugi_fdw/tsurugi_fdw.cpp
Fix for #192 .
```bash
DROP DATABASE
ALTER DATABASE
test test_preparation             ... ok           44 ms
test create_table                 ... ok          113 ms
test create_index                 ... ok           68 ms
test insert_select_happy          ... ok          285 ms
test update_delete                ... ok          199 ms
test select_statements            ... ok          129 ms
test user_management              ... ok           18 ms
test udf_transaction              ... ok          472 ms
test prepare_statment             ... ok          452 ms
test …
```
> Fix a unused function.

- expected/select_statements.out
- sql/select_statements.sql
- src/tsurugi_fdw/deparse.c
- src/tsurugi_fdw/tsurugi_fdw.cpp
- src/tsurugi_planner/tsurugi_planner.c
- Fix tsurugi_planner() function.
- Fix some tests.
- Add some logs.
```bash
DROP DATABASE
ALTER DATABASE
test test_preparation             ... ok           42 ms
test create_table                 ... ok          116 ms
test create_index                 ... ok           69 ms
test insert_select_happy          ... ok          303 ms
test update_delete                ... ok          198 ms
test select_statements            ... ok          180 ms
test user_management              ... ok           23 ms
test udf_transaction              ... ok          521 ms
test …
```
> Fix tsurugi_planner(), tests and add some logs.

- expected/udf_transaction.out
Updated to the SQL-02014 message changed in Tsurugi 1.4.0.
~~~log
DROP DATABASE
ALTER DATABASE
test test_preparation             ... ok           28 ms
test create_table                 ... ok          149 ms
test create_index                 ... ok           72 ms
test insert_select_happy          ... ok          306 ms
test update_delete                ... ok          203 ms
test select_statements            ... ok          167 ms
test user_management              ... ok           21 ms
test udf_transaction              ... ok          501 ms
test prepare_statment …
> Updated to the SQL-02014 message changed in Tsurugi 1.4.0.

- Makefile
- Fix for using PG_CPPFLAGS
- Fix subdir in Makefile
```bash
DROP DATABASE
ALTER DATABASE
test test_preparation             ... ok           35 ms
test create_table                 ... ok          108 ms
test create_index                 ... ok           72 ms
test insert_select_happy          ... ok          377 ms
test update_delete                ... ok          194 ms
test select_statements            ... ok          168 ms
test user_management              ... ok           22 ms
test udf_transaction              ... ok          506 ms
test prepare_statment …
```
> Fix makefile.

- expected/create_table_restrict.out
- expected/test_preparation.out
Regression testing has improved.
```shell-session
$ pg_ctl --version
pg_ctl (PostgreSQL) 12.4
```
```shell-session
DROP DATABASE
ALTER DATABASE
test test_preparation             ... ok           12 ms
test create_table_happy           ... ok          222 ms
test create_index_happy           ... ok          192 ms
test insert_select_happy          ... ok          619 ms
test update_delete_happy          ... ok          410 ms
test select_statement_happy       ... ok          241 ms
test user_management_happy        ... ok          103 ms
test udf_transaction_happy …
```
> Fixed regression test expectations.

- Makefile
- expected/ddl_happy.out
- expected/ddl_unhappy.out
- expected/test_cleanup.out
- expected/udf_tg_show_tables_happy.out
- include/common/tsurugi.h
- sql/ddl_happy.sql
- sql/ddl_unhappy.sql
- sql/test_cleanup.sql
- src/common/connection.cpp
- src/common/tsurugi.cpp
- src/fdw/tsurugi_fdw.cpp
- src/fdw/tsurugi_options.cpp
- src/fdw/tsurugi_utils.cpp
- src/udf/tg_execute_ddl.cpp
- src/udf/tg_show_tables.cpp
- src/udf/tg_verify_tables.cpp
- tsurugi_fdw--1.2.0--1.3.0.sql
- tsurugi_fdw--1.3.0.sql
Includes the following additions and changes:
- Added functionality to set the Tsurugi database name.
- The default value of the user-defined function tg_show_tables() has changed.
- **PostgreSQL 12.22**
```shell-session
$ make USE_PGXS=1 tests
bash ./scripts/test.sh
make[1]: Entering directory '/home/postgres/.local/src/tsurugi_fdw/feature-tg_dbname'
/usr/local/postgres/12.22/lib/pgxs/src/makefiles/../../src/test/regress/pg_regress --inputdir=./ --bindir='/usr/local/postgres/12.22/bin'    --dbname=contrib_regression test_preparation ddl_happy dml_happy data_types_happy case_sensitive_happy prep_dml_happy prep_data_types_happy prep_case_sensitive_happy manual_tutorial udf_transaction_happy udf_tg_show_tables_happy udf_tg_verify_tables_happy import_foreign_schema_happy ddl_unhappy …
```
> Added functionality to set the Tsurugi database name. 

- expected/dml_happy.out
- expected/prep_data_types_happy.out
- sql/dml_happy.sql
- sql/prep_data_types_happy.sql
Includes the following additions and changes:
- Enabled CROSS JOIN testing.
- Deleted the TIME WITH TIME ZONE test.
- **PostgreSQL 12.22**
```shell-session
DROP DATABASE
ALTER DATABASE
test test_preparation             ... ok           22 ms
test ddl_happy                    ... ok        16275 ms
test dml_happy                    ... ok         1979 ms
test data_types_happy             ... ok         4748 ms
test case_sensitive_happy         ... ok          293 ms
test prep_dml_happy               ... ok         2558 ms
test prep_data_types_happy        ... ok …
```
> Fixed the test.
